// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBojfUDa2h8YSm2INcYWEQiGS7K_uKNdfQ',
    appId: '1:711363742594:web:2b4c55e0ded7b703dc1d9b',
    messagingSenderId: '711363742594',
    projectId: 'fir-app-545af',
    authDomain: 'fir-app-545af.firebaseapp.com',
    storageBucket: 'fir-app-545af.appspot.com',
    measurementId: 'G-GY414GE3B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6wOrIFlYezclFnxQRAygwilshUjFGfRM',
    appId: '1:711363742594:android:4267709fb7c19c9cdc1d9b',
    messagingSenderId: '711363742594',
    projectId: 'fir-app-545af',
    storageBucket: 'fir-app-545af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGudmRsQ21r-Vk4wscAMalYsccrU_q2W4',
    appId: '1:711363742594:ios:d7005fdd27d30f30dc1d9b',
    messagingSenderId: '711363742594',
    projectId: 'fir-app-545af',
    storageBucket: 'fir-app-545af.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
